# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: sumitdas76.Talkative
PackageVersion: 1.3.12
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ProductCode: '{7E1B3C52-9A44-4E0B-B7D1-52B4A46C1F0D}_is1'
ReleaseDate: 2026-10-03
AppsAndFeaturesEntries:
- DisplayName: Talkative version 1.3.12
  Publisher: Sumit Das
  ProductCode: '{7E1B3C52-9A44-4E0B-B7D1-52B4A46C1F0D}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/sumitdas76/talkative/releases/download/v1.3.12/TalkativeSetup.exe
  InstallerSha256: ACC0FB3F3F7FE20CC3F02438A6C135D22DE0F05C5A770C16655F5FD35836ECB1
ManifestType: installer
ManifestVersion: 1.12.0
